### ISSUE TITLE
Station vlan GOOSE control block required for switchyard lighting

### ISSUE THREAD

**Issue by jarradraumati** [danyill/oscd-tp-multicast-naming#21]
We use GOOSE to turn switchyard lighting off/on. It ideally should belong on a protection 1 station VLAN.

A generic station-wide GOOSE for non-protection applications would be nice. Or we create another GOOSE control block name that the plugin will process.

![image](https://github.com/danyill/oscd-tp-multicast-naming/assets/3224671/4c9ce45f-3ac5-4aa3-8dae-3bf2e55fb77b)

**Comment by danyill** [comment]
I think for us it should just be in the Slow GOOSE bucket with a suitable control block name.

How about "Light"?!

**Comment by danyill** [comment]
I settled on `SwydLighting`
