### ISSUE TITLE
Prot 1 GOOSE cannot use VLAN = 1002 to 1005 for Cisco

### ISSUE THREAD

**Issue by jarradraumati** [danyill/oscd-tp-multicast-naming#22]
Cisco switches do not allow the use of VLAN = 1002 to 1005.

https://community.cisco.com/t5/switching/use-of-vlan-1002-1005/td-p/1995034

The Prot 1 GOOSE VLAN should start at 1006 and end at 1054.
Prot 2 will be offset by 1000 as normal.

**Comment by jarradraumati** [comment]
Scratch the increase. It will overlap with the station GOOSE. Leave it at 1049.

**Comment by danyill** [comment]
I guess you tried it and it didn't work?
