### ISSUE TITLE
CSV Export - Final 3 column headers are incorrect

### ISSUE THREAD

**Issue by aus-betz** [danyill/oscd-tp-multicast-naming#27]
When using the CSV export feature, the final three column headers are mixed up. Shown order is Min Time, Max Time, ConfRev; whereas the order should be ConfRev, Min Time, Max Time.

![image](https://github.com/user-attachments/assets/c787039e-e984-4066-ab3d-5d3cad5552c2)

**Comment by aus-betz** [comment]
It appears we can blame @jarradraumati for this one! How cool is the blame tool... Line 1418 to be bumped to rows further down.
@danyill, I may need a quick lesson on github on how to address easy fixes like this and also how to suggest features.

![image](https://github.com/user-attachments/assets/739cf6ab-91fa-4a77-b07b-f15d4240f04d)

**Comment by jarradraumati** [comment]
The danger of not having tests and doing quick changes...

Fair straightforward to fix. I'll do a pull request soon.

**Comment by danyill** [comment]
Thanks for reporting :+1: 

I've redeployed to https://transpower-nz.github.io/open-scd/

You may need to do a Ctrl+F5 in your browser to refresh the distribution.

**Comment by danyill** [comment]
> @danyill, I may need a quick lesson on github on how to address easy fixes like this and also how to suggest features.

Sure, we can do a session, send me an invite
