### ISSUE TITLE
VTSelStn SMVs do not create a station VLAN 

### ISSUE THREAD

**Issue by jarradraumati** [danyill/oscd-tp-multicast-naming#9]
At present, we give station voltage SV streams an SMV id of `VTSelStn` to let the multicast naming editor know that a station VLAN should be created (e.g. `2050`).

This does not happen. See the attached scd file for an example.

[XAT (12) (1).zip](https://github.com/danyill/oscd-tp-multicast-naming/files/13312907/XAT.12.1.zip)

**Comment by TPChenDNZ** [comment]
I don't think the fix works for Prot 1 SCD file [project+B30+BusABSelected+Comm+Mappings+SELQualMap-TimeRef-GEFixApplied.zip](https://github.com/danyill/oscd-tp-multicast-naming/files/13741986/project%2BB30%2BBusABSelected%2BComm%2BMappings%2BSELQualMap-TimeRef-GEFixApplied.zip)

For example XAT_278_MU1_VTSelStn still get allocated VLAN 1001.

**Comment by jarradraumati** [comment]
Do a Ctrl-F5 refresh and try again. You should get this result:

![image](https://github.com/danyill/oscd-tp-multicast-naming/assets/3224671/42eb2d4c-234d-4e34-bcce-43ac82e6faeb)

**Comment by TPChenDNZ** [comment]
Some awful refresh problems. Tried twice. Both time I refreshed browser. Once worked once did not.
